### ISSUE TITLE
Implement Redis functionality with Batch mode (connect to dictionary)

### ISSUE THREAD

**Issue by azipp** [cmsc22000-project-2018/autocomplete#104]

**Comment by azipp** [comment]
Finished reworking dictionary files, and editing Makefile (#112 and #113)

**Comment by azipp** [comment]
compiles, but segfaults. Need to debug.
Waiting on API team to write a api function version of TRIE.COMPLETIONS function by tries team

**Comment by jeffreymzhou** [comment]
Continuing work with batch_mode.c and redis integration.
