### ISSUE TITLE
Import a new (mock) dictionary from scratch (batch)

### ISSUE THREAD

**Issue by azipp** [cmsc22000-project-2018/autocomplete#18]
Check if the dict is provided
Create if not, there is a default trie/dict stored on the server (make dummy program for that)
Make dummy program that sends the dict to the trie team, get a trie back, as a pointer to the server (from api team)

Work out how to have multiple input files (piping two files together) 
If we do a batch mode, have a file of prefixes and dict, then pipe them in
Research how to distinguish b/w them

**Comment by azipp** [comment]
For testing, we will create our own custom dictionary from only a small batch of words.
I'll be working on loading that into a phony trie (here, will probably load them into a linked list for now).

Will also write a get_children function that looks into the list, and returns the prefix_t struct as a result.

**Comment by dwahme** [comment]
Hey, I created a dictionary module that might make your life a bit easier. Check it out [here](https://github.com/cmsc22000-project-2018/spellcheck/wiki/Dictionary-Documentation) if you're interested.

**Comment by azipp** [comment]
Want to have everything in the command line, no redirection
