### ISSUE TITLE
Create real Travis CI files and functionality

### ISSUE THREAD

**Issue by SethDeVries** [cmsc22000-project-2018/autocomplete#28]

**Comment by azipp** [comment]
Notes from meeting: 
What unit tests could we run
what individual functions could we run
testing shells are tricky, maybe don't worry about it in this sprint
testing batch mode is an integration test
If you're working with travis on your own branch, need to configure it to work with that specific branch b/c it doesn't automatically run on all branches
But once you push it to dev, anyone else's commits could break the build if their code doesn't pass the travis tests you have 
definitely want to work on having tests on your repository
