### ISSUE TITLE
Improve command line arguments to ./autocomplete

### ISSUE THREAD

**Issue by SethDeVries** [cmsc22000-project-2018/autocomplete#29]
Add flags for batch mode flags, add flags to input files (dictionary input and prefixes input) to enable dictionary input to bash mode too, and dual dictionary/prefix input

**Comment by azipp** [comment]
For dictionary mode:

See getopt
ex: ./autocomplete -d dictionary.txt -t text.txt
Ex for redis: ./autcomplete -s redis.uchicago.edu
