### ISSUE TITLE
Change shell interactive mode to go straight to autocomplete (./autocomplete) 

### ISSUE THREAD

**Issue by dayaffe** [cmsc22000-project-2018/autocomplete#34]

**Comment by SethDeVries** [comment]
See #30

**Comment by dayaffe** [comment]
Note that this issue was created before the instructions on how to create them

Description: Need to change the shell command ./minishell to ./autocomplete where the shell automatically runs interactive mode

Process: Had to interrogate the code to determine how commands are run. Using a hard coded count of runs, I was able to determine startup and on startup, based on how commands are parsed, tell the shell to run autocomplete as if it was typed in as input right away.

Completion: This was completed with no bugs or issues. ./autocomplete runs the shell and jumps straight into the autocomplete command which runs interactive mode.

Note: This changes the command but does not yet support additional command-line arguments. That is a separate issue.
