### ISSUE TITLE
Decide on format for command line options

### ISSUE THREAD

**Issue by azipp** [cmsc22000-project-2018/autocomplete#39]

**Comment by SethDeVries** [comment]
I'm thinking we should do something along the lines of:
-d <dictionary file>
-f <prefixes file>
-w <show words>
-n <number of words>
Are there any complaints/suggestions?

**Comment by dayaffe** [comment]
Can you say what each one is for? Also we need a flag for when we pull from the server something like -s

**Comment by dayaffe** [comment]
Also what order different things are called. For example which dictionary source to use, as well as whether to do batch versus interactive.

**Comment by SethDeVries** [comment]
-d : dictionary
-f : file input (batch mode)
-w : show words (show if != 0) (batch mode only)
-n : number of words (batch mode only)

**Comment by dayaffe** [comment]
-s should be an alternative to -d i mean

**Comment by SethDeVries** [comment]
- I'm also adding an output file option for batch mode, under -o.
- I'd assume we default to the redis standard dictionary if the user doesn't provide one? Otherwise we could end up with 0 or more than 1 dictionaries defined, in which case whichever cl argument came second would take precedence

**Comment by SethDeVries** [comment]
Closing this issue because they're implemented, but these are easy enough to change / add to.
