### ISSUE TITLE
Add delete functionality during interactive mode

### ISSUE THREAD

**Issue by dayaffe** [cmsc22000-project-2018/autocomplete#46]
During interactive mode, users should probably be able to use delete when they mistype a word. Currently the program only supports perfect input.

Jonas 05.16: 
Only implemented single-word delete - that is, you can only delete the most recently typed word and have the autocomplete function still work - because we need to change the llist structure in order to delete more than one word. Saving that for Sprint 4

**Comment by misterzenzel** [comment]
Ended up taking a long time because I had to figure out a weird bug, as marked in the comments. Will close the issue once the pull request is approved!
